# Ejemplo del template alternativo más simple:
name: Deploy to Cloud Run from Source

on:
  push:
    branches: [main]

env:
  PROJECT_ID: propfinder-prod
  REGION: us-central1

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Deploy Backend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: propfinder-backend
          source: ./backend
          region: ${{ env.REGION }}
